GET http://localhost:8000/api/conversations/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MTI5NjcyLCJpYXQiOjE3NjYxMjYwNzIsImp0aSI6IjhiOTI2YTM0NGYxZTQ2NmE5MzBhZTllNmM0YzExMmQzIiwidXNlcl9pZCI6IjEifQ.1bI1vb6dRJ7dEvhMYtIago6Roo92Oaryz_bAWDhEdCc

###
POST http://localhost:8000/api/conversations/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MTI5NjcyLCJpYXQiOjE3NjYxMjYwNzIsImp0aSI6IjhiOTI2YTM0NGYxZTQ2NmE5MzBhZTllNmM0YzExMmQzIiwidXNlcl9pZCI6IjEifQ.1bI1vb6dRJ7dEvhMYtIago6Roo92Oaryz_bAWDhEdCc

{
    "title": "Hello World"
}

###
PUT http://localhost:8000/api/conversations/13/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MTI5NjcyLCJpYXQiOjE3NjYxMjYwNzIsImp0aSI6IjhiOTI2YTM0NGYxZTQ2NmE5MzBhZTllNmM0YzExMmQzIiwidXNlcl9pZCI6IjEifQ.1bI1vb6dRJ7dEvhMYtIago6Roo92Oaryz_bAWDhEdCc

{
    "title": "Hello World2"
}

###
GET http://localhost:8000/api/conversations/13/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MTI5NjcyLCJpYXQiOjE3NjYxMjYwNzIsImp0aSI6IjhiOTI2YTM0NGYxZTQ2NmE5MzBhZTllNmM0YzExMmQzIiwidXNlcl9pZCI6IjEifQ.1bI1vb6dRJ7dEvhMYtIago6Roo92Oaryz_bAWDhEdCc

###
DELETE http://localhost:8000/api/conversations/15/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MTI5NjcyLCJpYXQiOjE3NjYxMjYwNzIsImp0aSI6IjhiOTI2YTM0NGYxZTQ2NmE5MzBhZTllNmM0YzExMmQzIiwidXNlcl9pZCI6IjEifQ.1bI1vb6dRJ7dEvhMYtIago6Roo92Oaryz_bAWDhEdCc
###
POST http://localhost:8000/api/conversations/13/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MTI5NjcyLCJpYXQiOjE3NjYxMjYwNzIsImp0aSI6IjhiOTI2YTM0NGYxZTQ2NmE5MzBhZTllNmM0YzExMmQzIiwidXNlcl9pZCI6IjEifQ.1bI1vb6dRJ7dEvhMYtIago6Roo92Oaryz_bAWDhEdCc

{
    "message": "How are you?"
}

###
PUT http://localhost:8000/api/conversations/11/messages/22/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MTI5NjcyLCJpYXQiOjE3NjYxMjYwNzIsImp0aSI6IjhiOTI2YTM0NGYxZTQ2NmE5MzBhZTllNmM0YzExMmQzIiwidXNlcl9pZCI6IjEifQ.1bI1vb6dRJ7dEvhMYtIago6Roo92Oaryz_bAWDhEdCc

{
    "role": "user",
    "content": "What are you?"
}

###
DELETE http://localhost:8000/api/conversations/11/messages/21/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MTI5NjcyLCJpYXQiOjE3NjYxMjYwNzIsImp0aSI6IjhiOTI2YTM0NGYxZTQ2NmE5MzBhZTllNmM0YzExMmQzIiwidXNlcl9pZCI6IjEifQ.1bI1vb6dRJ7dEvhMYtIago6Roo92Oaryz_bAWDhEdCc

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test@test"
}

###
POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json  

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NTk2NzI2NCwiaWF0IjoxNzY1ODgwODY0LCJqdGkiOiJjNTczNWYxNDQ3MGU0ODZmODU2YTU4NTYxMzM1MGEyNiIsInVzZXJfaWQiOiIxIn0.tkF1MSeNZB-d79E3QTLFALcylGyrCUrIMdNMuIJQxo8"
}
