GET http://localhost:8000/api/conversations/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MDc0MTM2LCJpYXQiOjE3NjYwNzA1MzYsImp0aSI6IjVmYmJkZTg1ZWIwNjQ3ZGE4Njc5NjMxMDczZTFmMzQwIiwidXNlcl9pZCI6IjEifQ.vQtr1We3zE44gffWLdTIQJi8fhUdJdBGke4p5EG7vEg

###
POST http://localhost:8000/api/conversations/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MDc0MTM2LCJpYXQiOjE3NjYwNzA1MzYsImp0aSI6IjVmYmJkZTg1ZWIwNjQ3ZGE4Njc5NjMxMDczZTFmMzQwIiwidXNlcl9pZCI6IjEifQ.vQtr1We3zE44gffWLdTIQJi8fhUdJdBGke4p5EG7vEg

{
    "title": "Hello World"
}

###
PUT http://localhost:8000/api/conversations/13/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MDc0MTM2LCJpYXQiOjE3NjYwNzA1MzYsImp0aSI6IjVmYmJkZTg1ZWIwNjQ3ZGE4Njc5NjMxMDczZTFmMzQwIiwidXNlcl9pZCI6IjEifQ.vQtr1We3zE44gffWLdTIQJi8fhUdJdBGke4p5EG7vEg

{
    "title": "Hello World1"
}

###
GET http://localhost:8000/api/conversations/13/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MDc0MTM2LCJpYXQiOjE3NjYwNzA1MzYsImp0aSI6IjVmYmJkZTg1ZWIwNjQ3ZGE4Njc5NjMxMDczZTFmMzQwIiwidXNlcl9pZCI6IjEifQ.vQtr1We3zE44gffWLdTIQJi8fhUdJdBGke4p5EG7vEg

###
DELETE http://localhost:8000/api/conversations/11/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MDc0MTM2LCJpYXQiOjE3NjYwNzA1MzYsImp0aSI6IjVmYmJkZTg1ZWIwNjQ3ZGE4Njc5NjMxMDczZTFmMzQwIiwidXNlcl9pZCI6IjEifQ.vQtr1We3zE44gffWLdTIQJi8fhUdJdBGke4p5EG7vEg

###
POST http://localhost:8000/api/conversations/13/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MDc0MTM2LCJpYXQiOjE3NjYwNzA1MzYsImp0aSI6IjVmYmJkZTg1ZWIwNjQ3ZGE4Njc5NjMxMDczZTFmMzQwIiwidXNlcl9pZCI6IjEifQ.vQtr1We3zE44gffWLdTIQJi8fhUdJdBGke4p5EG7vEg

{
    "message": "How are you?"
}

###
PUT http://localhost:8000/api/conversations/11/messages/20/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MDc0MTM2LCJpYXQiOjE3NjYwNzA1MzYsImp0aSI6IjVmYmJkZTg1ZWIwNjQ3ZGE4Njc5NjMxMDczZTFmMzQwIiwidXNlcl9pZCI6IjEifQ.vQtr1We3zE44gffWLdTIQJi8fhUdJdBGke4p5EG7vEg

{
    "role": "user",
    "content": "What are you?"
}

###
DELETE http://localhost:8000/api/conversations/11/messages/20/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MDc0MTM2LCJpYXQiOjE3NjYwNzA1MzYsImp0aSI6IjVmYmJkZTg1ZWIwNjQ3ZGE4Njc5NjMxMDczZTFmMzQwIiwidXNlcl9pZCI6IjEifQ.vQtr1We3zE44gffWLdTIQJi8fhUdJdBGke4p5EG7vEg

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test@test"
}

###
POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json  

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NTk2NzI2NCwiaWF0IjoxNzY1ODgwODY0LCJqdGkiOiJjNTczNWYxNDQ3MGU0ODZmODU2YTU4NTYxMzM1MGEyNiIsInVzZXJfaWQiOiIxIn0.tkF1MSeNZB-d79E3QTLFALcylGyrCUrIMdNMuIJQxo8"
}
